# Generated by Django 4.0.6 on 2022-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('subject_name', models.CharField(max_length=100)),
                ('marks_got', models.CharField(max_length=100)),
            ],
        ),
    ]
