# Generated by Django 3.2.18 on 2023-05-15 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('artist_id', models.IntegerField(unique=True)),
                ('artist_mail', models.EmailField(max_length=254)),
                ('artist_department', models.CharField(max_length=50)),
                ('artist_designation', models.CharField(max_length=50)),
                ('artist_reporting', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shot1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('shot_name', models.CharField(max_length=50)),
                ('task_assign', models.CharField(max_length=100)),
                ('work_description', models.CharField(max_length=200)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_status', models.CharField(max_length=100)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
