# Generated by Django 3.2.18 on 2023-05-30 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('project_name', models.CharField(max_length=100)),
                ('shot_name', models.CharField(max_length=100)),
                ('issuedate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shot2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(choices=[('Tejas', 'Tejas'), ('BNG', 'BNG'), ('Jawan', 'Jawan'), ('Soup', 'Soup')], max_length=100)),
                ('shot_name', models.CharField(max_length=100)),
                ('task_assign', models.CharField(choices=[('VFX', 'VFX'), ('Roto', 'Roto'), ('Paint', 'Paint'), ('Supervisor', 'Supervisor'), ('Comp', 'Comp'), ('Production', 'Production'), ('Editor', 'Editor'), ('Matchmove', 'Matchmove'), ('MGFX', 'MGFX'), ('DMP', 'DMP'), ('Pipeline', 'Pipeline'), ('IT', 'IT')], max_length=100)),
                ('work_description', models.CharField(max_length=200)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_status', models.CharField(choices=[('YTS', 'YTS'), ('WIP', 'WIP'), ('Done', 'Done')], max_length=100)),
                ('eta', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True)),
                ('department', models.CharField(choices=[('VFX', 'VFX'), ('Roto', 'Roto'), ('Paint', 'Paint'), ('Supervisor', 'Supervisor'), ('Comp', 'Comp'), ('Production', 'Production'), ('Editor', 'Editor'), ('Matchmove', 'Matchmove'), ('MGFX', 'MGFX'), ('DMP', 'DMP'), ('Pipeline', 'Pipeline'), ('IT', 'IT')], max_length=40)),
                ('designation', models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('TD', 'TD'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('HOD', 'HOD')], max_length=40)),
                ('reporting', models.CharField(choices=[('Mr. Riaz patel', 'Mr. Riaz patel'), ('Mr. Abhishek Kulkarni', 'Mr. Abhishek Kulkarni'), ('Mr. Swapnil Kharche', 'Mr. Swapnil Kharche'), ('Mr. Vinay', 'Mr. Vinay')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('shot_name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('WIP', 'WIP'), ('Done', 'Done')], max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=100)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
