# Generated by Django 4.1.3 on 2023-01-29 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Ename', models.CharField(max_length=100)),
                ('Elastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Edepart', models.CharField(max_length=100)),
                ('Edesg', models.CharField(max_length=100)),
                ('Epay', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
