# Generated by Django 4.0.6 on 2022-07-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleimg', models.FileField(blank=True, null=True, upload_to='Gallery')),
            ],
        ),
    ]
