# Generated by Django 3.2.19 on 2023-06-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(choices=[('YTS', 'YTS'), ('WIP', 'WIP'), ('DONE', 'DONE')], max_length=100, verbose_name='Shot Status')),
                ('department', models.CharField(max_length=40)),
                ('project_name', models.CharField(max_length=100)),
                ('shot_name', models.CharField(max_length=100)),
                ('issuedate', models.DateField(auto_now=True)),
                ('eta', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True)),
                ('department', models.CharField(choices=[('VFX', 'VFX'), ('Roto', 'Roto'), ('Paint', 'Paint'), ('CG', 'CG'), ('Supervisor', 'Supervisor'), ('Comp', 'Comp'), ('Production', 'Production'), ('Editor', 'Editor'), ('Matchmove', 'Matchmove'), ('MGFX', 'MGFX'), ('DMP', 'DMP'), ('Pipeline', 'Pipeline'), ('IT', 'IT')], max_length=40)),
                ('designation', models.CharField(choices=[('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Data IO', 'Data IO'), ('Jr. Artist', 'Jr. Artist'), ('Sr. Artist', 'Sr. Artist'), ('Pipeline TD', 'Pipeline TD'), ('Coordinator', 'Coordinator'), ('Team Lead', 'Team Lead'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('HOD', 'HOD')], max_length=40)),
                ('reporting', models.CharField(choices=[('Mr. Riaz patel', 'Mr. Riaz patel'), ('Mr. Abhishek Kulkarni', 'Mr. Abhishek Kulkarni'), ('Mr. Swapnil Kharche', 'Mr. Swapnil Kharche'), ('Mr. Vinay Kadam', 'Mr. Vinay Kadam'), ('Mr. Kunal Salunkhe', 'Mr. Kunal Salunkhe'), ('Ms. Ankita Goyal', 'Ms. Ankita Goyal'), ('Mr. Bhushan Pawar', 'Mr. Bhushan Pawar')], max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25, verbose_name='Project Name')),
                ('shot_name', models.CharField(max_length=25, verbose_name='Shot Name')),
                ('work_description', models.CharField(max_length=200, verbose_name='Scope of Work')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted')),
                ('work_status', models.CharField(choices=[('YTS', 'YTS'), ('WIP', 'WIP'), ('DONE', 'DONE')], max_length=100, verbose_name='Shot Status')),
                ('eta', models.DateField(blank=True, default=None, null=True, verbose_name='TGT Date (y-m-d)')),
                ('dependency', models.ManyToManyField(to='user.StudentExtra', verbose_name='Dependencies')),
            ],
        ),
        migrations.CreateModel(
            name='SendFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
                ('shot_name', models.CharField(max_length=25)),
                ('content', models.TextField(max_length=100)),
                ('work_status', models.CharField(choices=[('YTS', 'YTS'), ('WIP', 'WIP'), ('DONE', 'DONE')], max_length=25)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=100)),
                ('issued_shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.issuedshot')),
                ('sender1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shot2')),
            ],
        ),
    ]
