# Generated by Django 3.2.19 on 2023-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_managementmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedshot',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
