# Generated by Django 4.0.6 on 2022-07-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=100)),
                ('stumail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('stuid', 'subject')},
            },
        ),
    ]
