# Generated by Django 4.0.6 on 2022-07-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentdata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.IntegerField()),
                ('date1', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='attendance.studentdata1', to_field='stuid_sub')),
            ],
            options={
                'unique_together': {('ip_address', 'date1'), ('uid', 'date1')},
            },
        ),
    ]
