# Generated by Django 4.0.6 on 2022-07-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_mark_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(unique=True)),
                ('stuname', models.CharField(max_length=100)),
                ('stumail', models.EmailField(max_length=100)),
            ],
        ),
    ]
