# Generated by Django 4.0.6 on 2022-08-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_mark_attendance2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_id', models.IntegerField()),
                ('lap_name', models.CharField(max_length=100)),
                ('lap_model', models.CharField(max_length=100)),
            ],
        ),
    ]
